language: generic
sudo: required
dist: trusty
os:
  - osx
  - linux
osx_image: xcode10
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
jobs:
  include:
    - stage: "Unit Tests"
      script:  "make test"
    - stage: "Integration Tests"
      script:  "make integration_test"
      if: (os = osx)
