language: generic
sudo: required
dist: trusty
os:
  - osx
  - linux
osx_image: xcode10
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
stages:
  - name: "Unit Tests"
    script:  "make test"
  - name: "Integration Tests"
    script:  "make integration_test"
    if: (os = osx)
