language: generic
osx_image: xcode10
jobs:
    include:
        - stage: "test"
          script: "make test"
          sudo: required
          dist: trusty
          install:
              - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
          os:
            - osx
            - linux
        - stage: "integration"
          script: "make integration_test"
          os:
            - osx
