language: generic
sudo: required
dist: trusty
os:
  - osx
  - linux
osx_image: xcode10
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
- name: "Unit Tests"
  script:  "make test"
- if: (os = osx)
  - name: "Integration Tests"
    script:  "make integration_test"
